스토리보드 디자인 적용 ver.1
ZZANZU/TTURIYO_android pull request #2
Opened 2018-05-25 04:00 UTC by ZZANZU

2018-05-27 07:10 UTC, kujyp requested changes

2018-05-27 07:10 UTC, kujyp commented on app/src/main/java/io/github/tturiyo/tturiyo_android/ui/customer/CustomerHomeProductViewHolder.kt
> +    var companyImage: ImageView = itemView!!.findViewById(R.id.customer_home_product_img)
https://kotlinlang.org/docs/tutorials/android-plugin.html#view-binding

CustomerHomeProductViewHolder.kt
```
class CustomerHomeProductViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
    fun bind(item: CustomerHomeProduct) {
        Log.d()

        itemView.customer_home_product_img.setImageResource(item.companyImage)
        itemView.customer_home_product_company.text = item.companyName
        itemView.customer_home_product_name.text = item.productName
        itemView.customer_home_product_cost_before.text = item.productPriceBefore
        itemView.customer_home_product_cost_after.text = item.productPriceAfter
        itemView.customer_home_product_surplus.text = item.productSurplus
    }
}
```

CustomerHomeProductAdapter.kt
```
override fun onBindViewHolder(holder: CustomerHomeProductViewHolder, position: Int) {
    Log.d()
    holder.bind(productItems[position])
}
```

2018-05-27 07:10 UTC, kujyp commented on app/src/main/res/drawable/rounded_corner.xml
> +    <solid android:color="@color/white"/>
이것도 가능함 `@android:color/white`

2018-05-27 07:13 UTC, kujyp commented on app/src/main/java/io/github/tturiyo/tturiyo_android/ui/customer/CustomerHomeSearchFragment.kt
> +        val mapFragment = mView.findViewById(R.id.customer_search_map) as MapView
synthetic property사용가능

2018-05-27 17:24 UTC, ZZANZU commented on app/src/main/java/io/github/tturiyo/tturiyo_android/ui/customer/CustomerHomeProductViewHolder.kt
> +    var companyImage: ImageView = itemView!!.findViewById(R.id.customer_home_product_img)
wow

2018-05-27 17:33 UTC, ZZANZU commented on app/src/main/java/io/github/tturiyo/tturiyo_android/ui/customer/CustomerHomeSearchFragment.kt
> +        val mapFragment = mView.findViewById(R.id.customer_search_map) as MapView
val mapFragment = mView.customer_search_map as MapView
이렇게?

2018-05-28 05:38 UTC, kujyp approved these changes

2018-05-28 07:09 UTC, merged